name: Sync Leetcode (With Descriptions)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync
      uses: dos-m0nk3y/LeetCode-Synchronizer@v1.2.0
      with:
        GITHUB_TOKEN: ${{ github.token }}
        LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
